settings:
  output: docs/news/
  maxitems: 30
  throttle: 2
  timeout: 30
  verbose: true

feeds:
  - title: Comics - Kill Six Billion Demons
    url: https://killsixbilliondemons.com/feed/
  - title: Comics - Oglaf
    url: http://oglaf.com/feeds/rss/
  - title: Comics - Order of the Stick
    url: https://www.giantitp.com/comics/oots.rss
  - title: Comics - xkcd
    url: https://xkcd.com/rss.xml
  #- title: Comics - Schlock
  #  url: https://www.schlockmercenary.com/rss/

  - title: News - SVT Norrbotten
    url: https://www.svt.se/nyheter/lokalt/norrbotten/rss.xml
  - title: News - SVT Vetenskap
    url: https://www.svt.se/nyheter/vetenskap/rss.xml
  #- title: News - SVT Inrikes
  #  url: https://www.svt.se/nyheter/inrikes/rss.xml
  #- title: News - SVT Utrikes
  #  url: https://www.svt.se/nyheter/utrikes/rss.xml
  #- title: News - SVT Ekonomi
  #  url: https://www.svt.se/nyheter/ekonomi/rss.xml

  - title: LTU - Nyheter
    url: https://www.ltu.se/ltu/media/news?mode=rss
  - title: LTU - Studentnyheter
    url: https://www.ltu.se/student/Studentnyheter?mode=rss
  - title: LTU - Studentnotiser
    url: https://www.ltu.se/student/Studentnotiser?mode=rss

  - title: Blogs - research!rsc
    url: https://research.swtch.com/feed.atom
  - title: Blogs - Filippo Valsorda
    url: https://words.filippo.io/rss/
  - title: Blogs - Schneier
    url: https://www.schneier.com/blog/atom.xml
  - title: Blogs - Bartosz Ciechanowski
    url: https://ciechanow.ski/atom.xml

  - title: Services - DuckDuckGo
    url: https://spreadprivacy.com/rss/
  - title: Services - Let's Encrypt
    url: https://letsencrypt.org/feed.xml
  - title: Services - Mozilla
    url: https://blog.mozilla.org/security/feed/
  - title: Services - Libera.chat
    url: https://libera.chat/atom.xml
  - title: Services - SourceHut
    url: https://sourcehut.org/blog/index.xml
  - title: Services - Golang
    url: https://go.dev/blog/feed.atom
  - title: Services - FreeBSD
    url: https://www.freebsd.org/news/feed.xml

  - title: Tech - /r/Programming
    url: https://old.reddit.com/r/programming/top/.rss?sort=top&t=week&limit=20
  #- title: Tech - /r/Golang
  #  url: https://old.reddit.com/r/golang/top/.rss?sort=top&t=week&limit=20
  #- title: Tech - /r/Netsec
  #  url: https://old.reddit.com/r/netsec/top/.rss?sort=top&t=week&limit=20
  #- title: Tech - TorrentFreak
  #  url: https://torrentfreak.com/feed/
  - title: Tech - Hacker News
    url: https://hnrss.org/frontpage?link=comments&comments=25&points=50
    parser:
      rule: (?sU)<item>.*<title><!\[CDATA\[(?P<title>[^\]]+)\]\]></title>.*<comments>(?P<url>[^<]+)</comments>.*</item>
      host: https://hnrss.org/best?link=comments&comments=25&points=50
    #url: https://news.ycombinator.com/rss
    #parser:
    #  rule: (?sU)<item>.*<title>(?P<title>[^<]+)</title>.*<comments>(?P<url>[^<]+)</comments>.*</item>
    #  host: https://news.ycombinator.com/rss
