settings:
  output: docs/news/
  template: .feedloggr.html
  maxdays: 30
  maxitems: 30
  timeout: 30
  jitter: 5
  verbose: true

feeds:
  - title: Comics - Ten Earth Shattering Blows
    url: https://tenearthshatteringblows.com/feed
  - title: Comics - Kill Six Billion Demons
    url: https://killsixbilliondemons.com/feed/
  - title: Comics - Oglaf
    url: http://oglaf.com/feeds/rss/
  - title: Comics - Order of the Stick
    url: https://www.giantitp.com/comics/oots.rss
  - title: Comics - xkcd
    url: https://xkcd.com/rss.xml
  #- title: Comics - Schlock
  #  url: https://www.schlockmercenary.com/rss/

  - title: News - SVT Norrbotten
    url: https://www.svt.se/nyheter/lokalt/norrbotten/rss.xml
  - title: News - SVT Vetenskap
    url: https://www.svt.se/nyheter/vetenskap/rss.xml

  - title: LTU - Nyheter
    url: https://www.ltu.se/ltu/media/news?mode=rss
  - title: LTU - Studentnyheter
    url: https://www.ltu.se/student/Studentnyheter?mode=rss
  - title: LTU - Studentnotiser
    url: https://www.ltu.se/student/Studentnotiser?mode=rss

  - title: Blogs - research!rsc
    url: https://research.swtch.com/feed.atom
  - title: Blogs - Filippo Valsorda
    url: https://words.filippo.io/rss/
  - title: Blogs - Schneier
    url: https://www.schneier.com/blog/atom.xml
  - title: Blogs - Bartosz Ciechanowski
    url: https://ciechanow.ski/atom.xml

  - title: Services - Let's Encrypt
    url: https://letsencrypt.org/feed.xml
  - title: Services - Mozilla
    url: https://blog.mozilla.org/security/feed/
  - title: Services - Golang
    url: https://go.dev/blog/feed.atom
  - title: Services - FreeBSD
    url: https://www.freebsd.org/news/feed.xml

  - title: Tech - programming.dev/c/programming
    url: https://programming.dev/feeds/c/programming.xml?sort=TopWeek
  - title: Tech - beehaw.org/c/programming
    url: https://beehaw.org/feeds/c/programming.xml?sort=TopWeek
    parser:
      rule: (?sU)<item>.*<title>(?P<title>[^<]+)</title>.*<comments>(?P<url>[^<]+)</comments>.*</item>
  - title: Tech - kbin.social/m/programming
    url: https://kbin.social/rss?magazine=programming&sortBy=top
  - title: Tech - lobste.rs
    url: https://lobste.rs/top.rss
    parser:
      rule: (?sU)<item>.*<title>(?P<title>[^<]+)</title>.*<comments>(?P<url>[^<]+)</comments>.*</item>
  - title: Tech - Hacker News
    url: https://hnrss.org/best?link=comments&comments=25&points=50
    # parser:
    #   rule: (?sU)<item>.*<title><!\[CDATA\[(?P<title>[^\]]+)\]\]></title>.*<comments>(?P<url>[^<]+)</comments>.*</item>
    #   host: https://hnrss.org/best?link=comments&comments=25&points=50
    #url: https://news.ycombinator.com/rss
    #parser:
    #  rule: (?sU)<item>.*<title>(?P<title>[^<]+)</title>.*<comments>(?P<url>[^<]+)</comments>.*</item>
    #  host: https://news.ycombinator.com/rss
