settings:
  output: docs/news/
  template: .feedloggr.html
  maxdays: 30
  maxitems: 10
  timeout: 30
  jitter: 5
  verbose: true

feeds:
  - title: Comics - Ten Earth Shattering Blows
    url: https://tenearthshatteringblows.com/feed
  - title: Comics - Kill Six Billion Demons
    url: https://killsixbilliondemons.com/feed/
  - title: Comics - Oglaf
    url: http://oglaf.com/feeds/rss/
  - title: Comics - Order of the Stick
    url: https://www.giantitp.com/comics/oots.rss
  - title: Comics - xkcd
    url: https://xkcd.com/rss.xml
  - title: Comics - Rising Sand
    url: http://risingsand.glass/feed/
  - title: Comics - Saga
    url: https://imagecomics.com/comics/list/series/saga/releases
    parser:
      rule: (?sU)cover-image.+<a\shref="(?P<url>[^"]+)">.*<span[^>]*>(?P<title>[^<]+)\s*</span>

  - title: News - SVT Norrbotten
    url: https://www.svt.se/nyheter/lokalt/norrbotten/rss.xml
  - title: News - SVT Vetenskap
    url: https://www.svt.se/nyheter/vetenskap/rss.xml

  # - title: LTU - Nyheter
    # url: https://www.ltu.se/ltu/media/news?mode=rss
  # - title: LTU - Studentnyheter
    # url: https://www.ltu.se/student/Studentnyheter?mode=rss
  # - title: LTU - Studentnotiser
    # url: https://www.ltu.se/student/Studentnotiser?mode=rss
  - title: LTU - Nyheter
    url: https://www.ltu.se/4.110defe1188bd8d55c026619/12.110defe1188bd8d55c026626.portlet?state=rss&sv.contenttype=text/xml;charset=utf-8

  - title: Blogs - research!rsc
    url: https://research.swtch.com/feed.atom
  - title: Blogs - Filippo Valsorda
    url: https://words.filippo.io/rss/
  - title: Blogs - Schneier
    url: https://www.schneier.com/blog/atom.xml
  - title: Blogs - Bartosz Ciechanowski
    url: https://ciechanow.ski/atom.xml
  - title: Blogs - Ploum.net
    url: https://ploum.net/atom_en.xml
  - title: Blogs - nicole@web
    url: https://ntietz.com/atom.xml
  - title: Blogs - Halfspace
    url: https://buttondown.email/j2kun/rss
  - title: Blogs - Julia Evans
    url: https://jvns.ca/atom.xml
  - title: Blogs - Evan Prodromou
    url: https://evanp.me/feed/
  - title: Blogs - Factorio
    url: https://factorio.com/blog/rss
  - title: Blogs - Daemonic Dispatches
    url: https://www.daemonology.net/blog/index.rss
  - title: Blogs - Armin Ronacher's Thoughts and Writings
    url: https://lucumr.pocoo.org/feed.atom

  - title: Services - Let's Encrypt
    url: https://letsencrypt.org/feed.xml
  - title: Services - Mozilla
    url: https://blog.mozilla.org/security/feed/
  - title: Services - Golang
    url: https://go.dev/blog/feed.atom
  - title: Services - FreeBSD
    url: https://www.freebsd.org/news/feed.xml
  - title: Services - Debian
    url: https://www.debian.org/News/news
  - title: Services - Forgejo
    url: https://forgejo.org/rss.xml

  - title: Tech - lobste.rs
    url: https://lobste.rs/top.rss
    parser:
      rule: (?sU)<item>.*<title>(?P<title>[^<]+)</title>.*<comments>(?P<url>[^<]+)</comments>.*</item>
  - title: Tech - Hacker News
    url: https://news.ycombinator.com/over?points=300
    parser:
      rule: (?sU)<span class="titleline"><a[^>]*>(?P<title>[^<]+)</a>.*<span class="age"[^>]*><a href="(?P<url>[^"]+)">
      host: https://news.ycombinator.com/best
