settings:
  output: www/feeds/
  maxitems: 30
  throttle: 2
  timeout: 30
  verbose: true

feeds:
  - title: Comics - Dresden Codak
    url: https://dresdencodak.com/feed/
  - title: Comics - Kill Six Billion Demons
    url: https://killsixbilliondemons.com/feed/
  - title: Comics - Oglaf
    url: http://oglaf.com/feeds/rss/
  - title: Comics - Order of the Stick
    url: https://www.giantitp.com/comics/oots.rss
  - title: Comics - Schlock
    url: https://www.schlockmercenary.com/rss/
  - title: Comics - xkcd
    url: https://xkcd.com/rss.xml
  - title: Comics - The Weekly Roll
    url: https://old.reddit.com/r/theweeklyroll/top/.rss?sort=top&t=week&limit=20

  - title: Reading - Longform
    url: https://longform.org/feed.rss
  - title: Reading - Wait But Why
    url: https://waitbutwhy.com/feed

  - title: News - SVT Norrbotten
    url: https://www.svt.se/nyheter/lokalt/norrbotten/rss.xml
  - title: News - SVT Inrikes
    url: https://www.svt.se/nyheter/inrikes/rss.xml
  - title: News - SVT Utrikes
    url: https://www.svt.se/nyheter/utrikes/rss.xml
  - title: News - SVT Vetenskap
    url: https://www.svt.se/nyheter/vetenskap/rss.xml
  - title: News - SVT Ekonomi
    url: https://www.svt.se/nyheter/ekonomi/rss.xml
  
  - title: LTU - Nyheter
    url: https://www.ltu.se/ltu/media/news?mode=rss
  - title: LTU - Studentnyheter
    url: https://www.ltu.se/student/Studentnyheter?mode=rss
  - title: LTU - Studentnotiser
    url: https://www.ltu.se/student/Studentnotiser?mode=rss
    
  - title: Services - DuckDuckGo
    url: https://spreadprivacy.com/rss/
  - title: Services - Fastmail
    url: https://fastmail.blog/rss/
  - title: Services - Let's Encrypt
    url: https://letsencrypt.org/feed.xml
  - title: Services - Mozilla
    url: https://blog.mozilla.org/security/feed/
  - title: Services - Github
    url: https://github.blog/feed/
  - title: Services - Libera.chat
    url: https://libera.chat/atom.xml
    
  - title: Golang - Blog
    url: https://blog.golang.org/feed.atom
  - title: Golang - Ardan Labs
    url: https://www.ardanlabs.com/blog/index.xml
  - title: Golang - research!rsc
    url: https://research.swtch.com/feed.atom
  - title: Golang - /r/Golang
    url: https://old.reddit.com/r/golang/top/.rss?sort=top&t=week&limit=20

  - title: Tech - /r/Programming
    url: https://old.reddit.com/r/programming/top/.rss?sort=top&t=week&limit=20
  - title: Tech - /r/Netsec
    url: https://old.reddit.com/r/netsec/top/.rss?sort=top&t=week&limit=20
  - title: Tech - Cryptography Dispatches
    url: https://buttondown.email/cryptography-dispatches/rss
  - title: Tech - Schneier
    url: https://www.schneier.com/blog/atom.xml
  - title: Tech - The Cheapskate's Guide
    url: https://cheapskatesguide.org/cheapskates-guide-rss-feed.xml
  - title: Tech - TorrentFreak
    url: https://torrentfreak.com/feed/
  - title: Tech - Bartosz Ciechanowski
    url: https://ciechanow.ski/atom.xml

  - title: Tech - Hacker News
    url: https://news.ycombinator.com/
    parser:
      rule: (?sU)class="titlelink"[^>]*>(?P<title>[^<]+)</a>.*<a href="(?P<url>[^"]*)">\d+&nbsp;comments
      host: https://news.ycombinator.com/
