site: https://www.larus.se
title-prefix: Larus.se
author: Alex
css: /style/theme.css
lang: en

header:
  - <a href="https://github.com/lmas" rel="noopener nofollow">Code</a>
  - <a href="/news/">News</a>
  - <a href="/docs/notes/">Notes</a>
  - <a href="/docs/refs/">Refs</a>
  - <a href="/docs/snips/">Snips</a>

footer:
  # - <a href="/feed.xml">Feed</a>
  # - <a href="https://github.com/lmas/lmas.github.io" rel="noopener nofollow">Source</a>
  # - <a href="/stats/">Visitors</a>
  # - <a href="/legal/">Legal</a>

