 title: Larus.se
 author: Alex
 short: The personal homepage for Alex
 logo: /style/larus.png
 site: https://www.larus.se
 github: https://github.com/lmas
 mail: hello@larus.se
 source: https://github.com/lmas/larus.se
 copyright: Copyright © 2021 Alex
