name: Build blog
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - name: Build and deploy blog
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL}}
        run: make buildblog
