name: Build news

env:
  branch: gh-pages

on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'

      - name: Install dependencies
        run: |
          go install github.com/lmas/feedloggr@v0.4.0
          sed -e 's/.feedloggr.html/tmpl/g' .feedloggr.yml > conf
          cp .feedloggr.html tmpl
          cp .scripts/randomcommitmsg randmsg

      - name: Build news
        run: |
          git fetch --depth 1 origin $branch
          git switch $branch
          feedloggr -conf conf run

      - name: Deploy build
        run: |
          git add --all docs/news
          git config --local user.name "gullbot"
          git config --local user.email "gullbot@larus.se"
          ./randmsg | git commit --file -
          git push
