name: Build feeds
on:
  schedule:
    - cron: '30 17 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - name: Build and deploy feeds
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL}}
        run: make buildfeeds
