name: Update feeds

on:
  schedule:
    # Everyday at 4 in the morning, UTC
    - cron: '0 4 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it in `cwd`.
      # Also enables git commands, for more info see: https://stackoverflow.com/a/58393457
      - uses: actions/checkout@v2
        with:
          ref: public
          fetch-depth: 0

      - name: Merge master
        run: |
          git config --global user.name 'Gull-Bot'
          git config --global user.email 'gull-bot@larus.se'
          git merge origin/master

      - name: Update feeds
        run: make feeds

      - name: Commit files
        run: |
          git add -A public/
          git commit -m "Automated feeds update $(date '+%Y-%m-%d')"
          git push

      - name: Deploy
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
        run: curl "$DEPLOY_URL"

